apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boot-k8s-sample-deploy
  labels:
    app.kubernetes.io/name: boot-k8s-sample-deploy
    app.kubernetes.io/part-of: boot-k8s-sample-deploy-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boot-k8s-sample-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80