apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-k8s-sample-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boot-k8s-sample-deploy
  template:
    metadata:
      labels:
        app: boot-k8s-sample-deploy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - boot-k8s-sample-deploy
              topologyKey: kubernetes.io/hostname
      containers:
      - name: boot-k8s-sample-deploy
        image: vinaybalamuru/boot-k8s-sample-deploy:PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: boot-k8s-sample-deploy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: boot-k8s-sample-deploy 