apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: boot-k8s-sample-deploy
  app.kubernetes.io/name: boot-k8s-sample-deploy
  app.kubernetes.io/part-of: boot-k8s-sample-deploy

commonAnnotations:
  app.kubernetes.io/description: "Spring Boot Application"
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0" 